// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: sage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sage_GetUser_FullMethodName            = "/Sage/GetUser"
	Sage_UpdateUser_FullMethodName         = "/Sage/UpdateUser"
	Sage_CreateUser_FullMethodName         = "/Sage/CreateUser"
	Sage_GetFeed_FullMethodName            = "/Sage/GetFeed"
	Sage_LikeUser_FullMethodName           = "/Sage/LikeUser"
	Sage_UnlikeUser_FullMethodName         = "/Sage/UnlikeUser"
	Sage_GetLikes_FullMethodName           = "/Sage/GetLikes"
	Sage_GetMatches_FullMethodName         = "/Sage/GetMatches"
	Sage_CreatePresignedURL_FullMethodName = "/Sage/CreatePresignedURL"
)

// SageClient is the client API for Sage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SageClient interface {
	// User
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// Feed
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
	// Match
	LikeUser(ctx context.Context, in *LikeUserRequest, opts ...grpc.CallOption) (*LikeUserResponse, error)
	UnlikeUser(ctx context.Context, in *UnlikeUserRequest, opts ...grpc.CallOption) (*UnlikeUserResponse, error)
	GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error)
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error)
	// Presigned URL
	CreatePresignedURL(ctx context.Context, in *CreatePresignedURLRequest, opts ...grpc.CallOption) (*CreatePresignedURLResponse, error)
}

type sageClient struct {
	cc grpc.ClientConnInterface
}

func NewSageClient(cc grpc.ClientConnInterface) SageClient {
	return &sageClient{cc}
}

func (c *sageClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, Sage_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, Sage_UpdateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, Sage_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	out := new(GetFeedResponse)
	err := c.cc.Invoke(ctx, Sage_GetFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) LikeUser(ctx context.Context, in *LikeUserRequest, opts ...grpc.CallOption) (*LikeUserResponse, error) {
	out := new(LikeUserResponse)
	err := c.cc.Invoke(ctx, Sage_LikeUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) UnlikeUser(ctx context.Context, in *UnlikeUserRequest, opts ...grpc.CallOption) (*UnlikeUserResponse, error) {
	out := new(UnlikeUserResponse)
	err := c.cc.Invoke(ctx, Sage_UnlikeUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error) {
	out := new(GetLikesResponse)
	err := c.cc.Invoke(ctx, Sage_GetLikes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error) {
	out := new(GetMatchesResponse)
	err := c.cc.Invoke(ctx, Sage_GetMatches_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) CreatePresignedURL(ctx context.Context, in *CreatePresignedURLRequest, opts ...grpc.CallOption) (*CreatePresignedURLResponse, error) {
	out := new(CreatePresignedURLResponse)
	err := c.cc.Invoke(ctx, Sage_CreatePresignedURL_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SageServer is the server API for Sage service.
// All implementations must embed UnimplementedSageServer
// for forward compatibility
type SageServer interface {
	// User
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// Feed
	GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error)
	// Match
	LikeUser(context.Context, *LikeUserRequest) (*LikeUserResponse, error)
	UnlikeUser(context.Context, *UnlikeUserRequest) (*UnlikeUserResponse, error)
	GetLikes(context.Context, *GetLikesRequest) (*GetLikesResponse, error)
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesResponse, error)
	// Presigned URL
	CreatePresignedURL(context.Context, *CreatePresignedURLRequest) (*CreatePresignedURLResponse, error)
	mustEmbedUnimplementedSageServer()
}

// UnimplementedSageServer must be embedded to have forward compatible implementations.
type UnimplementedSageServer struct {
}

func (UnimplementedSageServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedSageServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedSageServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSageServer) GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (UnimplementedSageServer) LikeUser(context.Context, *LikeUserRequest) (*LikeUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeUser not implemented")
}
func (UnimplementedSageServer) UnlikeUser(context.Context, *UnlikeUserRequest) (*UnlikeUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikeUser not implemented")
}
func (UnimplementedSageServer) GetLikes(context.Context, *GetLikesRequest) (*GetLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikes not implemented")
}
func (UnimplementedSageServer) GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
}
func (UnimplementedSageServer) CreatePresignedURL(context.Context, *CreatePresignedURLRequest) (*CreatePresignedURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePresignedURL not implemented")
}
func (UnimplementedSageServer) mustEmbedUnimplementedSageServer() {}

// UnsafeSageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SageServer will
// result in compilation errors.
type UnsafeSageServer interface {
	mustEmbedUnimplementedSageServer()
}

func RegisterSageServer(s grpc.ServiceRegistrar, srv SageServer) {
	s.RegisterService(&Sage_ServiceDesc, srv)
}

func _Sage_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_GetFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_LikeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).LikeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_LikeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).LikeUser(ctx, req.(*LikeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_UnlikeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).UnlikeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_UnlikeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).UnlikeUser(ctx, req.(*UnlikeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_GetLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).GetLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_GetLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).GetLikes(ctx, req.(*GetLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_GetMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_CreatePresignedURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePresignedURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).CreatePresignedURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_CreatePresignedURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).CreatePresignedURL(ctx, req.(*CreatePresignedURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sage_ServiceDesc is the grpc.ServiceDesc for Sage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Sage",
	HandlerType: (*SageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Sage_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Sage_UpdateUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Sage_CreateUser_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _Sage_GetFeed_Handler,
		},
		{
			MethodName: "LikeUser",
			Handler:    _Sage_LikeUser_Handler,
		},
		{
			MethodName: "UnlikeUser",
			Handler:    _Sage_UnlikeUser_Handler,
		},
		{
			MethodName: "GetLikes",
			Handler:    _Sage_GetLikes_Handler,
		},
		{
			MethodName: "GetMatches",
			Handler:    _Sage_GetMatches_Handler,
		},
		{
			MethodName: "CreatePresignedURL",
			Handler:    _Sage_CreatePresignedURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sage.proto",
}
