// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: sage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sage_CreateUser_FullMethodName  = "/Sage/CreateUser"
	Sage_MessageUser_FullMethodName = "/Sage/MessageUser"
)

// SageClient is the client API for Sage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SageClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	MessageUser(ctx context.Context, opts ...grpc.CallOption) (Sage_MessageUserClient, error)
}

type sageClient struct {
	cc grpc.ClientConnInterface
}

func NewSageClient(cc grpc.ClientConnInterface) SageClient {
	return &sageClient{cc}
}

func (c *sageClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, Sage_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sageClient) MessageUser(ctx context.Context, opts ...grpc.CallOption) (Sage_MessageUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &Sage_ServiceDesc.Streams[0], Sage_MessageUser_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sageMessageUserClient{stream}
	return x, nil
}

type Sage_MessageUserClient interface {
	Send(*MessageUserRequest) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type sageMessageUserClient struct {
	grpc.ClientStream
}

func (x *sageMessageUserClient) Send(m *MessageUserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sageMessageUserClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SageServer is the server API for Sage service.
// All implementations must embed UnimplementedSageServer
// for forward compatibility
type SageServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	MessageUser(Sage_MessageUserServer) error
	mustEmbedUnimplementedSageServer()
}

// UnimplementedSageServer must be embedded to have forward compatible implementations.
type UnimplementedSageServer struct {
}

func (UnimplementedSageServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSageServer) MessageUser(Sage_MessageUserServer) error {
	return status.Errorf(codes.Unimplemented, "method MessageUser not implemented")
}
func (UnimplementedSageServer) mustEmbedUnimplementedSageServer() {}

// UnsafeSageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SageServer will
// result in compilation errors.
type UnsafeSageServer interface {
	mustEmbedUnimplementedSageServer()
}

func RegisterSageServer(s grpc.ServiceRegistrar, srv SageServer) {
	s.RegisterService(&Sage_ServiceDesc, srv)
}

func _Sage_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SageServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sage_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SageServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sage_MessageUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SageServer).MessageUser(&sageMessageUserServer{stream})
}

type Sage_MessageUserServer interface {
	Send(*Message) error
	Recv() (*MessageUserRequest, error)
	grpc.ServerStream
}

type sageMessageUserServer struct {
	grpc.ServerStream
}

func (x *sageMessageUserServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sageMessageUserServer) Recv() (*MessageUserRequest, error) {
	m := new(MessageUserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Sage_ServiceDesc is the grpc.ServiceDesc for Sage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Sage",
	HandlerType: (*SageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Sage_CreateUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageUser",
			Handler:       _Sage_MessageUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sage.proto",
}
