services:
  ${APP_SERVICE_NAME}:
    image: ${APP_SERVICE_NAME}
    container_name: ${APP_SERVICE_NAME}
    depends_on:
      - ${DB_SERVICE_NAME}
    build: go
    volumes:
      - ./go:/${APP_SERVICE_NAME}
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    entrypoint: ["./entrypoint.dev.sh"]

  ${DB_SERVICE_NAME}:
    image: ${DB_REPO}:${DB_IMAGE_TAG}
    container_name: ${DB_SERVICE_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    env_file:
      - .env
    volumes:
      - ${DB_SERVICE_NAME}:/data/${DB_SERVICE_NAME}
    ports:
      - ${DB_PORT}:27017

volumes:
  ${DB_SERVICE_NAME}:

networks:
  sage:
