services:
  db:
    container_name: slide_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: slide
    ports:
      - 27017:27017
    volumes:
      - ./slide-db:/home/mongodb
      - ./slide-db/data:/data/db
      - ./slide-db/scripts:/docker-entrypoint-initdb.d
  server:
    container_name: slide_server
    depends_on:
      - db
    env_file:
      - ./slide-server/.env.dev
    build:
      context: ./slide-server
      dockerfile: Dockerfile
    volumes:
      - ./slide-server:/usr/src/server
    ports:
      - 3000:3000

networks:
  slide:
