services:
  ${APP_NAME}:
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    depends_on:
      - ${DB_NAME}
    build: app
    volumes:
      - ./app:/${APP_NAME}
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_NAME}
    entrypoint: ["./entrypoint.dev.sh"]

  ${DB_NAME}:
    image: ${DB_ENGINE}:${DB_IMAGE_TAG}
    container_name: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ${DB_NAME}:/data/${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}

  ${WSS_SERVICE_NAME}:
    image: ${WSS_SERVICE_NAME}
    container_name: ${WSS_SERVICE_NAME}
    depends_on:
      - ${DB_NAME}
    build: wss
    volumes:
      - ./wss:/${WSS_SERVICE_NAME}
    ports:
      - ${WSS_PORT}:${WSS_PORT}
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_NAME}
    entrypoint: ["./entrypoint.dev.sh"]

volumes:
  ${DB_NAME}:

networks:
  ${APP_NAME}:
