services:
  ${APP_NAME}:
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    depends_on:
      - ${DB_NAME}
    build: ${APP_PATH}
    volumes:
      - ./${APP_PATH}:/${APP_NAME}
    ports:
      - ${APP_CONTAINER_PORT}:${APP_CONTAINER_PORT}
    env_file:
      - ${ENV_PATH}
    environment:
      - DB_DOMAIN=${DB_NAME}
      - DB_USERNAME=username
      - DB_PASSWORD=password
      - APPLE_SKIP_AUTH_CHECKS=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-west-2
      - APPLE_CLIENT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    entrypoint: ["./entrypoint.dev.sh"]

  ${DB_NAME}:
    image: ${DB_ENGINE}:${DB_IMAGE_TAG}
    container_name: ${DB_NAME}
    env_file:
      - ${ENV_PATH}
    volumes:
      - ${DB_NAME}:/data/${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

volumes:
  ${DB_NAME}:

networks:
  ${APP_NAME}:
