services:
  ${APP_CONTAINER_NAME}:
    image: ${APP_CONTAINER_NAME}
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - ${DB_CONTAINER_NAME}
    build: go
    volumes:
      - ./go:/${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:${APP_PORT}
    entrypoint: ["./entrypoint.dev.sh"]

  ${DB_CONTAINER_NAME}:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ${DB_CONTAINER_NAME}:/data/${DB_CONTAINER_NAME}
    ports:
      - ${DB_PORT}:27017

volumes:
  ${DB_CONTAINER_NAME}:

networks:
  sage:
