apiVersion: v1
data:
  APP_CONTAINER_NAME: c2FnZV9hcHA=
  APP_DB_NAME: c2FnZV9hcHA=
  APP_DB_PORT: MzAwMQ==
  APP_DB_SERVICE_NAME: YXBwX2Ri
  APP_DB_TABLE_NAME: dXNlcnM=
  APP_DB_URI: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQGFwcF9kYjoyNzAxNw==
  APP_SERVICE_NAME: YXBw
  APP_SERVICE_PORT: MzAwMA==
  AUTH_CONTAINER_NAME: c2FnZV9hdXRo
  AUTH_DB_NAME: c2FnZV9hdXRo
  AUTH_DB_PORT: NjAwMQ==
  AUTH_DB_SERVICE_NAME: YXV0aF9kYg==
  AUTH_DB_TABLE_NAME: dG9rZW5z
  AUTH_DB_URI: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQGF1dGhfZGI6MjcwMTc=
  AUTH_SERVICE_KEY_ID: SFVQOEw2MjdMTg==
  AUTH_SERVICE_KEY_PATH: QXV0aEtleV9IVVA4TDYyN0xOLnA4
  AUTH_SERVICE_NAME: YXV0aA==
  AUTH_SERVICE_PORT: NjAwMA==
  AUTH_SERVICE_TEAM_ID: TkxWTkpZNEZWVA==
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_USERNAME: dXNlcm5hbWU=
  SIGNALING_CONTAINER_NAME: c2FnZV9zaWduYWxpbmc=
  SIGNALING_DB_NAME: c2FnZV9zaWduYWxpbmc=
  SIGNALING_DB_PORT: NDAwMQ==
  SIGNALING_DB_SERVICE_NAME: c2lnbmFsaW5nX2Ri
  SIGNALING_DB_TABLE_NAME: cm91dGVz
  SIGNALING_DB_URI: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQHNpZ25hbGluZ19kYjoyNzAxNw==
  SIGNALING_SERVICE_NAME: c2lnbmFsaW5n
  SIGNALING_SERVICE_PORT: NDAwMA==
kind: Secret
metadata:
  name: my-secret
type: Opaque
