apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-deployment
  ports:
    - protocol: TCP
      port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
