apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
        - name: db-deployment
          image: "{{ .Values.registry }}/{{ .Values.repository }}:{{ .Values.dbTag }}"
          ports:
            - containerPort: "{{ .Values.dbPort }}"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-deployment-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-deployment-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.dbName }}"

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-deployment
  ports:
    - protocol: TCP
      port: "{{ .Values.dbPort }}"
      targetPort: "{{ .Values.dbPort }}"
