apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.DNS_SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: {{ .Values.DNS_SERVICE_NAME }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.DNS_SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: {{ .Values.DNS_SERVICE_NAME }}
rules:
  - apiGroups: [""]
    resources: ["services","endpoints","pods","nodes"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.DNS_SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: {{ .Values.DNS_SERVICE_NAME }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.DNS_SERVICE_NAME }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.DNS_SERVICE_NAME }}
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.DNS_SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: {{ .Values.DNS_SERVICE_NAME }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.DNS_SERVICE_NAME }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.DNS_SERVICE_NAME }}
    spec:
      serviceAccountName: {{ .Values.DNS_SERVICE_NAME }}
      containers:
        - name: {{ .Values.DNS_SERVICE_NAME }}
          image: registry.k8s.io/external-dns/external-dns:v0.14.0
          args:
            - --source=service
            - --source=ingress
            - --domain-filter={{ .Values.APP_DOMAIN }} 
            - --provider=aws
            - --registry=txt
            - --txt-owner-id={{ .Values.DNS_SERVICE_NAME }}
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.AWS_REGION }}