services:
  ${APP_SERVICE_NAME}:
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - ${DB_SERVICE_NAME}
    env_file:
      - ./.env.dev
    build:
      context: ./${APP_SERVICE_NAME}
      dockerfile: Dockerfile.dev
    volumes:
      - ./${APP_SERVICE_NAME}:/usr/src/
    ports:
      - ${APP_SERVICE_PORT}:${APP_SERVICE_PORT}

  ${DB_SERVICE_NAME}:
    container_name: ${APP_CONTAINER_NAME}_db
    image: mongo:6
    env_file:
      - ./.env.dev
    build:
      context: ./${APP_SERVICE_NAME}/db
      dockerfile: Dockerfile.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ${DB_SERVICE_NAME}:/data/db
      - ./${APP_SERVICE_NAME}/db/scripts:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:27017

volumes:
  ${DB_SERVICE_NAME}:

networks:
  sage:
