services:
  # App server
  app:
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - app_db
    env_file:
      - ./.env.dev
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/usr/src/
    ports:
      - ${APP_SERVICE_PORT}:${APP_SERVICE_PORT}

  app_db:
    container_name: ${APP_CONTAINER_NAME}_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ${APP_MONGO_DB_NAME}
    volumes:
      - ./app/db/data:/data/db
      - ./app/db/scripts:/docker-entrypoint-initdb.d
    ports:
      - ${APP_MONGO_PORT}:27017

  # Signaling server
  signaling:
    container_name: ${SIGNALING_CONTAINER_NAME}
    depends_on:
      - signaling_db
    env_file:
      - ./.env.dev
    build:
      context: ./signaling
      dockerfile: Dockerfile.dev
    volumes:
      - ./signaling:/usr/src/
    ports:
      - ${SIGNALING_SERVICE_PORT}:${SIGNALING_SERVICE_PORT}

  signaling_db:
    container_name: ${SIGNALING_CONTAINER_NAME}_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ${SIGNALING_MONGO_DB_NAME}
    volumes:
      - ./signaling/db/data:/data/db
      - ./signaling/db/scripts:/docker-entrypoint-initdb.d
    ports:
      - ${SIGNALING_MONGO_PORT}:27017

  # Auth server
  auth:
    container_name: ${AUTH_CONTAINER_NAME}
    depends_on:
      - auth_db
    env_file:
      - ./.env.dev
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth:/usr/src/
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}

  auth_db:
    container_name: ${AUTH_CONTAINER_NAME}_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ${AUTH_MONGO_DB_NAME}
    volumes:
      - ./auth/db/data:/data/db
      - ./auth/db/scripts:/docker-entrypoint-initdb.d
    ports:
      - ${AUTH_MONGO_PORT}:27017

networks:
  sage:
