services:
  # App server
  app:
    container_name: sage_app
    depends_on:
      - app_db
    env_file:
      - ./app/.env.dev
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - ~/.aws:/root/.aws
    ports:
      - 3000:3000
  app_db:
    container_name: sage_app_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sage
    ports:
      - 27017:27017
    volumes:
      - ./app/db:/home/mongodb
      - ./app/db/data:/data/db
      - ./app/db/scripts:/docker-entrypoint-initdb.d

  # Wss server
  wss:
    container_name: sage_wss
    env_file:
      - ./wss/.env.dev
    build:
      context: ./wss
      dockerfile: Dockerfile
    volumes:
      - ./wss:/usr/src/wss
      - ~/.aws:/root/.aws
    ports:
      - 3001:3001

networks:
  sage:
