services:
  # App server
  app:
    container_name: sage_app
    depends_on:
      - app_db
    env_file:
      - ./app/.env.dev
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - ~/.aws:/root/.aws
    ports:
      - 3000:3000

  app_db:
    container_name: sage_app_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sage_app
    ports:
      - 3001:27017
    volumes:
      - ./app/db/data:/data/db
      - ./app/db/scripts:/docker-entrypoint-initdb.d

  # WSS server
  wss:
    container_name: sage_wss
    depends_on:
      - wss_db
    env_file:
      - ./wss/.env.dev
    build:
      context: ./wss
      dockerfile: Dockerfile
    volumes:
      - ./wss:/usr/src/wss
      - ~/.aws:/root/.aws
    ports:
      - 4000:4000

  wss_db:
    container_name: sage_wss_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sage_wss
    ports:
      - 4001:27017
    volumes:
      - ./wss/db/data:/data/db
      - ./wss/db/scripts:/docker-entrypoint-initdb.d

networks:
  sage:
