name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  lottie: ^3.1.0
  flutter:
    sdk: flutter
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  protobuf: ^3.1.0
  grpc: ^3.2.4
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  go_router: ^14.1.4
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  collection: ^1.18.0
  camera: ^0.11.0+1
  geolocator: ^12.0.0
  fluttertoast: ^8.2.6
  video_player: ^2.8.7
  http: ^1.2.1
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  numberpicker: ^2.1.2
  better_player: ^0.0.63

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/go.json
    - assets/ghost.json
    - assets/record.json
    - assets/casper.json
    - assets/authentic.json
    - assets/sage.json
