apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: app-deployment
          image: "{{ .Values.registry }}/{{ .Values.repository }}:{{ .Values.appTag }}"
          ports:
            - containerPort: {{ .Values.appPort }}
