apiVersion: v1
kind: ConfigMap
metadata:
  name: signaling-configmap
data:
  db_host: signaling-db-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling
  namespace: signaling
  labels:
    app: signaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signaling
  template:
    metadata:
      labels:
        app: signaling
    spec:
      containers:
        - name: signaling
          image: trumanpurnell/sage:signaling
          ports:
            - containerPort: ${SIGNALING_SERVICE_PORT}

---
apiVersion: v1
kind: Service
metadata:
  name: signaling-service
  namespace: signaling
spec:
  selector:
    app: signaling
  ports:
    - protocol: TCP
      port: ${SIGNALING_SERVICE_PORT}
      targetPort: ${SIGNALING_SERVICE_PORT}
  type: LoadBalancer
