apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_SERVICE_NAME }}
spec:
  selector:
    app: {{ .Values.APP_DEPLOYMENT_NAME }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.APP_PORT }}
      targetPort: {{ .Values.APP_PORT }}
