apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-deployment
  ports:
    - protocol: TCP
      port: {{ .Values.dbPort }}
      targetPort: {{ .Values.dbPort }}
