-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoNgzqHje4bWS9FpH
0+yABdFETAsfWuX+s21jtnc5jragCgYIKoZIzj0DAQehRANCAASxHlDnmNeoiPKT
kXfGcjcLuLz4rqX4T7Bg+iQeQSWPf/1wr/MCTFNnJ5l7adXqIJl3C6cxo5JiUcOZ
gE47BG+e
-----END PRIVATE KEY-----