apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db
  labels:
    app: app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: app-db
          image: trumanpurnell/sage:auth-db
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: ${APP_DB_NAME}

---
apiVersion: v1
kind: Service
metadata:
  name: app-db-service
spec:
  selector:
    app: app-db
  ports:
    - protocol: TCP
      port: ${APP_DB_PORT}
      targetPort: 27017
