tasks.turnup.app.ecs.register_task_definition:
  family: ${APP_CONTAINER_TASK_DEFINITION_NAME}
  containerDefinitions:
    - name: ${APP_NAME}
      image: ${SAGE_ACCOUNT_ID}.dkr.ecr.${SAGE_REGION}.amazonaws.com/${APP_ECR_REPO_NAME}:${APP_IMAGE_TAG}
      environmentFiles:
        - value: ${S3_ARN_PREFIX}${S3_ENV_BUCKET_NAME}/${ENV_PATH}
          type: s3
      secrets:
        - name: DB_USERNAME
          valueFrom: arn:aws:ssm:${SAGE_REGION}:${SAGE_ACCOUNT_ID}:parameter/DB_USERNAME
        - name: DB_PASSWORD
          valueFrom: arn:aws:ssm:${SAGE_REGION}:${SAGE_ACCOUNT_ID}:parameter/DB_PASSWORD
        - name: APPLE_CLIENT_SECRET
          valueFrom: arn:aws:secretsmanager:${SAGE_REGION}:${SAGE_ACCOUNT_ID}:secret:APPLE_CLIENT_SECRET
      logConfiguration:
        logDriver: awslogs
        options:
          awslogs-group: ${APP_NAME}-logs
          awslogs-region: ${SAGE_REGION}
          awslogs-stream-prefix: ${APP_NAME}
          awslogs-create-group: "true"
      portMappings:
        - containerPort: ${APP_CONTAINER_PORT}
          protocol: ${APP_CONTAINER_PROTOCOL}
          appProtocol: ${APP_CONTAINER_PROTOCOL_VERSION}
  executionRoleArn: $(role.turnup.iam.get_role.Role.Arn)
  taskRoleArn: $(role.turnup.iam.get_role.Role.Arn)
  networkMode: awsvpc
  requiresCompatibilities:
    - FARGATE
  cpu: "${APP_CONTAINER_CPU}"
  memory: "${APP_CONTAINER_MEMORY}"
  runtimePlatform:
    cpuArchitecture: ${APP_CONTAINER_ARCHITECTURE}
    operatingSystemFamily: ${APP_CONTAINER_OS_FAMILY}
---
tasks.turnup.wss.ecs.register_task_definition:
  family: ${WSS_CONTAINER_TASK_DEFINITION_NAME}
  containerDefinitions:
    - name: ${WSS_NAME}
      image: ${SAGE_ACCOUNT_ID}.dkr.ecr.${SAGE_REGION}.amazonaws.com/${WSS_ECR_REPO_NAME}:${WSS_IMAGE_TAG}
      environmentFiles:
        - value: ${S3_ARN_PREFIX}${S3_ENV_BUCKET_NAME}/${ENV_PATH}
          type: s3
      secrets:
        - name: DB_USERNAME
          valueFrom: arn:aws:ssm:${SAGE_REGION}:${SAGE_ACCOUNT_ID}:parameter/DB_USERNAME
        - name: DB_PASSWORD
          valueFrom: arn:aws:ssm:${SAGE_REGION}:${SAGE_ACCOUNT_ID}:parameter/DB_PASSWORD
        - name: APPLE_CLIENT_SECRET
          valueFrom: arn:aws:secretsmanager:${SAGE_REGION}:${SAGE_ACCOUNT_ID}:secret:APPLE_CLIENT_SECRET
      logConfiguration:
        logDriver: awslogs
        options:
          awslogs-group: ${WSS_NAME}-logs
          awslogs-region: ${SAGE_REGION}
          awslogs-stream-prefix: ${WSS_NAME}
          awslogs-create-group: "true"
      portMappings:
        - containerPort: ${WSS_CONTAINER_PORT}
          protocol: ${WSS_CONTAINER_PROTOCOL}
          appProtocol: ${WSS_CONTAINER_PROTOCOL_VERSION}
  executionRoleArn: $(role.turnup.iam.get_role.Role.Arn)
  taskRoleArn: $(role.turnup.iam.get_role.Role.Arn)
  networkMode: awsvpc
  requiresCompatibilities:
    - FARGATE
  cpu: "${WSS_CONTAINER_CPU}"
  memory: "${WSS_CONTAINER_MEMORY}"
  runtimePlatform:
    cpuArchitecture: ${WSS_CONTAINER_ARCHITECTURE}
    operatingSystemFamily: ${WSS_CONTAINER_OS_FAMILY}
