-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWwdrXbYZgmI8xCiW
SGhq54qHWbgFJNXda5V2DUyFE2KgCgYIKoZIzj0DAQehRANCAATMOXyxzpC910Yk
gkhtsguyhiKmZSo+iyXF6G3p3PqEdsHEOkqEQxP3Q0x7zYUdyYAPZYi0KFAWinj4
IzGVtJ2X
-----END PRIVATE KEY-----