package main

import (
	"log"

	"github.com/bb-labs/sage/pb"
	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

func main() {
	dbc := pg.Connect(&pg.Options{
		User:     "username",
		Password: "password",
		Database: "sagedb",
		Addr:     "localhost:5432",
	})
	defer dbc.Close()

	// Create the db schema
	for _, model := range []interface{}{(*pb.User)(nil)} {
		err := dbc.Model(model).CreateTable(&orm.CreateTableOptions{
			IfNotExists:   true,
			FKConstraints: true,
		})
		if err != nil {
			log.Fatalf("failed to create table: %v", err)
		}
	}

	users := []*pb.User{
		{
			Id:          "25",
			Name:        "Alice Smith",
			Email:       "alice.smith@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 12, Month: 5, Year: 1990},
			Location:    &pb.Location{Latitude: 34.0522, Longitude: -118.2437},
			Preferences: &pb.Preferences{AgeMin: 25, AgeMax: 35, Proximity: 50, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "18",
			Name:        "Bob Johnson",
			Email:       "bob.johnson@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 23, Month: 8, Year: 1985},
			Location:    &pb.Location{Latitude: 40.7128, Longitude: -74.0060},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "11",
			Name:        "Carol Williams",
			Email:       "carol.williams@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 4, Month: 3, Year: 1992},
			Location:    &pb.Location{Latitude: 37.7749, Longitude: -122.4194},
			Preferences: &pb.Preferences{AgeMin: 28, AgeMax: 38, Proximity: 75, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "1",
			Name:        "David Brown",
			Email:       "david.brown@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 15, Month: 9, Year: 1988},
			Location:    &pb.Location{Latitude: 51.5074, Longitude: -0.1278},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 50, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "14",
			Name:        "Eva Miller",
			Email:       "eva.miller@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 19, Month: 11, Year: 1995},
			Location:    &pb.Location{Latitude: 48.8566, Longitude: 2.3522},
			Preferences: &pb.Preferences{AgeMin: 25, AgeMax: 35, Proximity: 60, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "6",
			Name:        "Frank Wilson",
			Email:       "frank.wilson@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 30, Month: 6, Year: 1983},
			Location:    &pb.Location{Latitude: 34.0522, Longitude: -118.2437},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 80, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "13",
			Name:        "Grace Taylor",
			Email:       "grace.taylor@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 8, Month: 12, Year: 1991},
			Location:    &pb.Location{Latitude: 41.8781, Longitude: -87.6298},
			Preferences: &pb.Preferences{AgeMin: 28, AgeMax: 38, Proximity: 55, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "50",
			Name:        "Hank Anderson",
			Email:       "hank.anderson@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 17, Month: 4, Year: 1987},
			Location:    &pb.Location{Latitude: 35.6895, Longitude: 139.6917},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 90, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "7",
			Name:        "Ivy Thomas",
			Email:       "ivy.thomas@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 22, Month: 2, Year: 1993},
			Location:    &pb.Location{Latitude: 52.5200, Longitude: 13.4050},
			Preferences: &pb.Preferences{AgeMin: 26, AgeMax: 36, Proximity: 70, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "9",
			Name:        "Jack Martinez",
			Email:       "jack.martinez@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 5, Month: 7, Year: 1986},
			Location:    &pb.Location{Latitude: -33.8688, Longitude: 151.2093},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "39",
			Name:        "Leo Harris",
			Email:       "leo.harris@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 21, Month: 8, Year: 1985},
			Location:    &pb.Location{Latitude: 40.7128, Longitude: -74.0060},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "28",
			Name:        "Nick Lewis",
			Email:       "nick.lewis@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 14, Month: 9, Year: 1988},
			Location:    &pb.Location{Latitude: 51.5074, Longitude: -0.1278},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 50, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "24",
			Name:        "Olivia Robinson",
			Email:       "olivia.robinson@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 18, Month: 11, Year: 1995},
			Location:    &pb.Location{Latitude: 48.8566, Longitude: 2.3522},
			Preferences: &pb.Preferences{AgeMin: 25, AgeMax: 35, Proximity: 60, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "29",
			Name:        "Paul Walker",
			Email:       "paul.walker@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 29, Month: 6, Year: 1983},
			Location:    &pb.Location{Latitude: 34.0522, Longitude: -118.2437},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 80, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "48",
			Name:        "Quinn Hall",
			Email:       "quinn.hall@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 7, Month: 12, Year: 1991},
			Location:    &pb.Location{Latitude: 41.8781, Longitude: -87.6298},
			Preferences: &pb.Preferences{AgeMin: 28, AgeMax: 38, Proximity: 55, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "45",
			Name:        "Ryan Young",
			Email:       "ryan.young@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 16, Month: 4, Year: 1987},
			Location:    &pb.Location{Latitude: 35.6895, Longitude: 139.6917},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 90, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "32",
			Name:        "Sophie King",
			Email:       "sophie.king@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 21, Month: 2, Year: 1993},
			Location:    &pb.Location{Latitude: 52.5200, Longitude: 13.4050},
			Preferences: &pb.Preferences{AgeMin: 26, AgeMax: 36, Proximity: 70, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "2",
			Name:        "Tom Wright",
			Email:       "tom.wright@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 4, Month: 7, Year: 1986},
			Location:    &pb.Location{Latitude: -33.8688, Longitude: 151.2093},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "5",
			Name:        "Uma Baker",
			Email:       "uma.baker@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 12, Month: 5, Year: 1990},
			Location:    &pb.Location{Latitude: 34.0522, Longitude: -118.2437},
			Preferences: &pb.Preferences{AgeMin: 25, AgeMax: 35, Proximity: 50, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "17",
			Name:        "Vince Adams",
			Email:       "vince.adams@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 23, Month: 8, Year: 1985},
			Location:    &pb.Location{Latitude: 40.7128, Longitude: -74.0060},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "44",
			Name:        "Wendy Scott",
			Email:       "wendy.scott@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 4, Month: 3, Year: 1992},
			Location:    &pb.Location{Latitude: 37.7749, Longitude: -122.4194},
			Preferences: &pb.Preferences{AgeMin: 28, AgeMax: 38, Proximity: 75, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "35",
			Name:        "Xander Evans",
			Email:       "xander.evans@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 15, Month: 9, Year: 1988},
			Location:    &pb.Location{Latitude: 51.5074, Longitude: -0.1278},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 50, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "30",
			Name:        "Yara Collins",
			Email:       "yara.collins@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 19, Month: 11, Year: 1995},
			Location:    &pb.Location{Latitude: 48.8566, Longitude: 2.3522},
			Preferences: &pb.Preferences{AgeMin: 25, AgeMax: 35, Proximity: 60, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "46",
			Name:        "Zack Ramirez",
			Email:       "zack.ramirez@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 30, Month: 6, Year: 1983},
			Location:    &pb.Location{Latitude: 34.0522, Longitude: -118.2437},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 80, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "20",
			Name:        "Anna Clark",
			Email:       "anna.clark@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 8, Month: 12, Year: 1991},
			Location:    &pb.Location{Latitude: 41.8781, Longitude: -87.6298},
			Preferences: &pb.Preferences{AgeMin: 28, AgeMax: 38, Proximity: 55, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "49",
			Name:        "Ben Green",
			Email:       "ben.green@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 17, Month: 4, Year: 1987},
			Location:    &pb.Location{Latitude: 35.6895, Longitude: 139.6917},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 90, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "10",
			Name:        "Cathy Lewis",
			Email:       "cathy.lewis@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 22, Month: 2, Year: 1993},
			Location:    &pb.Location{Latitude: 52.5200, Longitude: 13.4050},
			Preferences: &pb.Preferences{AgeMin: 26, AgeMax: 36, Proximity: 70, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "22",
			Name:        "Danielle Wright",
			Email:       "danielle.wright@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 5, Month: 7, Year: 1986},
			Location:    &pb.Location{Latitude: -33.8688, Longitude: 151.2093},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "19",
			Name:        "Ethan Campbell",
			Email:       "ethan.campbell@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 13, Month: 10, Year: 1990},
			Location:    &pb.Location{Latitude: 34.0522, Longitude: -118.2437},
			Preferences: &pb.Preferences{AgeMin: 25, AgeMax: 35, Proximity: 50, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "26",
			Name:        "Fiona Mitchell",
			Email:       "fiona.mitchell@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 21, Month: 8, Year: 1985},
			Location:    &pb.Location{Latitude: 40.7128, Longitude: -74.0060},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "3",
			Name:        "George Carter",
			Email:       "george.carter@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 6, Month: 3, Year: 1992},
			Location:    &pb.Location{Latitude: 37.7749, Longitude: -122.4194},
			Preferences: &pb.Preferences{AgeMin: 28, AgeMax: 38, Proximity: 75, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "33",
			Name:        "Hannah Perez",
			Email:       "hannah.perez@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 14, Month: 9, Year: 1988},
			Location:    &pb.Location{Latitude: 51.5074, Longitude: -0.1278},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 50, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "15",
			Name:        "Isaac Roberts",
			Email:       "isaac.roberts@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 18, Month: 11, Year: 1995},
			Location:    &pb.Location{Latitude: 48.8566, Longitude: 2.3522},
			Preferences: &pb.Preferences{AgeMin: 25, AgeMax: 35, Proximity: 60, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "4",
			Name:        "Jasmine Evans",
			Email:       "jasmine.evans@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 29, Month: 6, Year: 1983},
			Location:    &pb.Location{Latitude: 34.0522, Longitude: -118.2437},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 80, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "38",
			Name:        "Kyle Turner",
			Email:       "kyle.turner@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 7, Month: 12, Year: 1991},
			Location:    &pb.Location{Latitude: 41.8781, Longitude: -87.6298},
			Preferences: &pb.Preferences{AgeMin: 28, AgeMax: 38, Proximity: 55, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "41",
			Name:        "Lily Phillips",
			Email:       "lily.phillips@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 16, Month: 4, Year: 1987},
			Location:    &pb.Location{Latitude: 35.6895, Longitude: 139.6917},
			Preferences: &pb.Preferences{AgeMin: 27, AgeMax: 37, Proximity: 90, Gender: []pb.Gender{pb.Gender_MAN}},
		},
		{
			Id:          "21",
			Name:        "Mike Richardson",
			Email:       "mike.richardson@example.com",
			Gender:      []pb.Gender{pb.Gender_MAN},
			Birthday:    &pb.Birthday{Day: 21, Month: 2, Year: 1993},
			Location:    &pb.Location{Latitude: 52.5200, Longitude: 13.4050},
			Preferences: &pb.Preferences{AgeMin: 26, AgeMax: 36, Proximity: 70, Gender: []pb.Gender{pb.Gender_WOMAN}},
		},
		{
			Id:          "27",
			Name:        "Nina Barnes",
			Email:       "nina.barnes@example.com",
			Gender:      []pb.Gender{pb.Gender_WOMAN},
			Birthday:    &pb.Birthday{Day: 4, Month: 7, Year: 1986},
			Location:    &pb.Location{Latitude: -33.8688, Longitude: 151.2093},
			Preferences: &pb.Preferences{AgeMin: 30, AgeMax: 40, Proximity: 100, Gender: []pb.Gender{pb.Gender_MAN}},
		},
	}

	for _, user := range users {
		_, err := dbc.Model(user).Insert()
		if err != nil {
			log.Fatalf("Error inserting user: %v", err)
		}
	}
}
