//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: sage.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// // // // // // // // // // // //
/// Service
/// // // // // // // // // // // //
///
/// Usage: instantiate `SageClient`, then call methods of this protocol to make API calls.
internal protocol SageClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: SageClientInterceptorFactoryProtocol? { get }

  func createUser(
    _ request: CreateUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<CreateUserRequest, CreateUserResponse>

  func messageUser(
    callOptions: CallOptions?,
    handler: @escaping (Message) -> Void
  ) -> BidirectionalStreamingCall<MessageUserRequest, Message>
}

extension SageClientProtocol {
  internal var serviceName: String {
    return "Sage"
  }

  /// Unary call to CreateUser
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createUser(
    _ request: CreateUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<CreateUserRequest, CreateUserResponse> {
    return self.makeUnaryCall(
      path: SageClientMetadata.Methods.createUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateUserInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to MessageUser
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func messageUser(
    callOptions: CallOptions? = nil,
    handler: @escaping (Message) -> Void
  ) -> BidirectionalStreamingCall<MessageUserRequest, Message> {
    return self.makeBidirectionalStreamingCall(
      path: SageClientMetadata.Methods.messageUser.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageUserInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension SageClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "SageNIOClient")
internal final class SageClient: SageClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: SageClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: SageClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the Sage service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: SageClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct SageNIOClient: SageClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: SageClientInterceptorFactoryProtocol?

  /// Creates a client for the Sage service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: SageClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// // // // // // // // // // // //
/// Service
/// // // // // // // // // // // //
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol SageAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: SageClientInterceptorFactoryProtocol? { get }

  func makeCreateUserCall(
    _ request: CreateUserRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<CreateUserRequest, CreateUserResponse>

  func makeMessageUserCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<MessageUserRequest, Message>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension SageAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return SageClientMetadata.serviceDescriptor
  }

  internal var interceptors: SageClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCreateUserCall(
    _ request: CreateUserRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<CreateUserRequest, CreateUserResponse> {
    return self.makeAsyncUnaryCall(
      path: SageClientMetadata.Methods.createUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateUserInterceptors() ?? []
    )
  }

  internal func makeMessageUserCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<MessageUserRequest, Message> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: SageClientMetadata.Methods.messageUser.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageUserInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension SageAsyncClientProtocol {
  internal func createUser(
    _ request: CreateUserRequest,
    callOptions: CallOptions? = nil
  ) async throws -> CreateUserResponse {
    return try await self.performAsyncUnaryCall(
      path: SageClientMetadata.Methods.createUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateUserInterceptors() ?? []
    )
  }

  internal func messageUser<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Message> where RequestStream: Sequence, RequestStream.Element == MessageUserRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: SageClientMetadata.Methods.messageUser.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageUserInterceptors() ?? []
    )
  }

  internal func messageUser<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Message> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == MessageUserRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: SageClientMetadata.Methods.messageUser.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMessageUserInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct SageAsyncClient: SageAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: SageClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: SageClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol SageClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'createUser'.
  func makeCreateUserInterceptors() -> [ClientInterceptor<CreateUserRequest, CreateUserResponse>]

  /// - Returns: Interceptors to use when invoking 'messageUser'.
  func makeMessageUserInterceptors() -> [ClientInterceptor<MessageUserRequest, Message>]
}

internal enum SageClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Sage",
    fullName: "Sage",
    methods: [
      SageClientMetadata.Methods.createUser,
      SageClientMetadata.Methods.messageUser,
    ]
  )

  internal enum Methods {
    internal static let createUser = GRPCMethodDescriptor(
      name: "CreateUser",
      path: "/Sage/CreateUser",
      type: GRPCCallType.unary
    )

    internal static let messageUser = GRPCMethodDescriptor(
      name: "MessageUser",
      path: "/Sage/MessageUser",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// // // // // // // // // // // //
/// Service
/// // // // // // // // // // // //
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol SageProvider: CallHandlerProvider {
  var interceptors: SageServerInterceptorFactoryProtocol? { get }

  func createUser(request: CreateUserRequest, context: StatusOnlyCallContext) -> EventLoopFuture<CreateUserResponse>

  func messageUser(context: StreamingResponseCallContext<Message>) -> EventLoopFuture<(StreamEvent<MessageUserRequest>) -> Void>
}

extension SageProvider {
  internal var serviceName: Substring {
    return SageServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateUser":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<CreateUserRequest>(),
        responseSerializer: ProtobufSerializer<CreateUserResponse>(),
        interceptors: self.interceptors?.makeCreateUserInterceptors() ?? [],
        userFunction: self.createUser(request:context:)
      )

    case "MessageUser":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<MessageUserRequest>(),
        responseSerializer: ProtobufSerializer<Message>(),
        interceptors: self.interceptors?.makeMessageUserInterceptors() ?? [],
        observerFactory: self.messageUser(context:)
      )

    default:
      return nil
    }
  }
}

/// // // // // // // // // // // //
/// Service
/// // // // // // // // // // // //
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol SageAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: SageServerInterceptorFactoryProtocol? { get }

  func createUser(
    request: CreateUserRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> CreateUserResponse

  func messageUser(
    requestStream: GRPCAsyncRequestStream<MessageUserRequest>,
    responseStream: GRPCAsyncResponseStreamWriter<Message>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension SageAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return SageServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return SageServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: SageServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateUser":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<CreateUserRequest>(),
        responseSerializer: ProtobufSerializer<CreateUserResponse>(),
        interceptors: self.interceptors?.makeCreateUserInterceptors() ?? [],
        wrapping: { try await self.createUser(request: $0, context: $1) }
      )

    case "MessageUser":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<MessageUserRequest>(),
        responseSerializer: ProtobufSerializer<Message>(),
        interceptors: self.interceptors?.makeMessageUserInterceptors() ?? [],
        wrapping: { try await self.messageUser(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

internal protocol SageServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'createUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateUserInterceptors() -> [ServerInterceptor<CreateUserRequest, CreateUserResponse>]

  /// - Returns: Interceptors to use when handling 'messageUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMessageUserInterceptors() -> [ServerInterceptor<MessageUserRequest, Message>]
}

internal enum SageServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Sage",
    fullName: "Sage",
    methods: [
      SageServerMetadata.Methods.createUser,
      SageServerMetadata.Methods.messageUser,
    ]
  )

  internal enum Methods {
    internal static let createUser = GRPCMethodDescriptor(
      name: "CreateUser",
      path: "/Sage/CreateUser",
      type: GRPCCallType.unary
    )

    internal static let messageUser = GRPCMethodDescriptor(
      name: "MessageUser",
      path: "/Sage/MessageUser",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
