name: Deploy AWS resources

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AWS resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Run awyes actions
        uses: bb-labs/awyes@main
        env:
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          TURN_USERNAME: ${{ secrets.TURN_USERNAME }}
          TURN_PASSWORD: ${{ secrets.TURN_PASSWORD }}
        with:
          action: repo apple.user.apple_client_secret apple.ssm sage cluster app wss db
