name: Turndown AWS resources

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Teardown all AWS resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Run awyes actions to teardown resources
        uses: bb-labs/awyes@main
        with:
          action: ^services.turndown ^listeners.turndown ^targets.turndown ^cluster.turndown ^load.turndown ^secrets.turndown ^repos.turndown ^env.turndown ^s3.turndown ^db.turndown ^security.turndown ^certs.turndown ^role.turndown
